### ISSUE TITLE
Some errors causing restart.

### ISSUE THREAD

**Issue by sliwma** [jackbayliss/Mission-Chief-Bot#36]
INFO: 06/26/2020 09:52:21 Exception list index out of range
INFO: 06/26/2020 09:52:21 Traceback (most recent call last):
  File "MissionChiefBot.py", line 64, in getbase
  File "MissionChiefBot.py", line 79, in doActions
  File "MissionChiefBot.py", line 119, in buildMissions
  File "MissionChiefBot.py", line 143, in despatchMissions
  File "MissionChiefBot.py", line 161, in despatchMission
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MissionChiefBot.py", line 334, in <module>
  File "MissionChiefBot.py", line 33, in __init__
  File "MissionChiefBot.py", line 66, in getbase
  File "MissionChiefBot.py", line 79, in doActions
  File "MissionChiefBot.py", line 119, in buildMissions
  File "MissionChiefBot.py", line 143, in despatchMissions
  File "MissionChiefBot.py", line 161, in despatchMission
IndexError: list index out of range

**Comment by jackbayliss** [comment]
@sliwma  This is due to the experimental config option, if you set it to false you won't see this error. Or message me on Discord for the new testing version 👍
