### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by JoshuaBilboe96** [jackbayliss/Mission-Chief-Bot#62]
The bot closed atomically? 
this what i found on debug
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MissionChiefBot.py", line 624, in <module>
  File "MissionChiefBot.py", line 50, in __init__
  File "MissionChiefBot.py", line 92, in getbase
  File "MissionChiefBot.py", line 50, in __init__
  File "MissionChiefBot.py", line 89, in getbase
  File "MissionChiefBot.py", line 101, in doActions
  File "MissionChiefBot.py", line 600, in hireStaff
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 23 (char 22)

INFO: 10/10/2020 11:16:23 Attempting login
INFO: 10/10/2020 11:20:09 Attempting login
INFO: 10/10/2020 11:20:18 Checking for transport
INFO: 10/10/2020 11:20:18 Despatching failed missions
INFO: 10/10/2020 11:20:21 Exception Extra data: line 1 column 23 (char 22)
INFO: 10/10/2020 11:20:21 Traceback (most recent call last):
  File "MissionChiefBot.py", line 87, in getbase
  File "MissionChiefBot.py", line 109, in doActions
AttributeError: 'MissionChiefBot' object has no attribute 'retry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MissionChiefBot.py", line 624, in <module>
  File "MissionChiefBot.py", line 50, in __init__
  File "MissionChiefBot.py", line 89, in getbase
  File "MissionChiefBot.py", line 101, in doActions
  File "MissionChiefBot.py", line 600, in hireStaff
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 23 (char 22)

**Comment by JoshuaBilboe96** [comment]
Sorry Solved it 
Delete laststarted.json in the json folder fixed the issue
