### ISSUE TITLE
[Bug] Start up bug on new bot.

### ISSUE THREAD

**Issue by saulworthy** [jackbayliss/Mission-Chief-Bot#70]
Launching the bot after updating. attempts to generate missions and hire staff. bot does not complete task and spits out this error code:

--- Logging error ---
Traceback (most recent call last):
  File "MissionChiefBot.py", line 90, in getbase
  File "MissionChiefBot.py", line 104, in doActions
  File "MissionChiefBot.py", line 634, in hireStaff
  File "json__init.py", line 293, in load
  File "json__init.py", line 357, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 23 (char 22)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MissionChiefBot.py", line 660, in <module>
  File "MissionChiefBot.py", line 52, in init
  File "MissionChiefBot.py", line 92, in getbase
  File "MissionChiefBot.py", line 104, in doActions
  File "MissionChiefBot.py", line 634, in hireStaff
  File "json__init.py", line 293, in load
  File "json__init.py", line 357, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 23 (char 22)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging__init.py", line 1081, in emit
  File "logging__init.py", line 925, in format
  File "logging__init.py", line 664, in format
  File "logging__init.py", line 369, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "MissionChiefBot.py", line 664, in <module>
  File "logging__init.py", line 2070, in info
  File "logging__init.py", line 1434, in info
  File "logging__init.py", line 1577, in _log
  File "logging__init.py", line 1587, in handle
  File "logging__init.py", line 1649, in callHandlers
  File "logging__init.py", line 950, in handle
  File "logging__init.py", line 1183, in emit
  File "logging__init.py", line 1089, in emit
Message: 'Error on line 660'
Arguments: ('JSONDecodeError', JSONDecodeError('Extra data: line 1 column 23 (char 22)'))

**Comment by vosje1990** [comment]
delete laststarted.json in json folder

**Comment by saulworthy** [comment]
Seems to have fixed thank you

**Comment by jackbayliss** [comment]
This shouldn’t occur on the premium version anymore- are you a premium user?

**Comment by jackbayliss** [comment]
Closing, as fixed- this is fixed on sponsor version- so.. I believe you're using an out of date version?
